/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 28

#include <stdio.h>
#include <source/rock/middle/Node-fwd.h>
#include <source/rock/middle/StringLiteral-fwd.h>
#include <source/rock/middle/FunctionDecl-fwd.h>
#include <source/rock/middle/FunctionCall-fwd.h>

void stack_push(struct _rock_middle__Node *node);
void stack_pop(struct _rock_middle__Node *node);

#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_STRING_LIT(); /* 28 */
YY_RULE(int) yy_NUMBER(); /* 27 */
YY_RULE(int) yy_DIV(); /* 26 */
YY_RULE(int) yy_TIMES(); /* 25 */
YY_RULE(int) yy_Value(); /* 24 */
YY_RULE(int) yy_MINUS(); /* 23 */
YY_RULE(int) yy_PLUS(); /* 22 */
YY_RULE(int) yy_Product(); /* 21 */
YY_RULE(int) yy_COMMA(); /* 20 */
YY_RULE(int) yy_CLOS_PAREN(); /* 19 */
YY_RULE(int) yy_ExpressionList(); /* 18 */
YY_RULE(int) yy_OPEN_PAREN(); /* 17 */
YY_RULE(int) yy_CLOS_BRACK(); /* 16 */
YY_RULE(int) yy_Line(); /* 15 */
YY_RULE(int) yy_OPEN_BRACK(); /* 14 */
YY_RULE(int) yy_Body(); /* 13 */
YY_RULE(int) yy__(); /* 12 */
YY_RULE(int) yy_COLON(); /* 11 */
YY_RULE(int) yy_FunctionDecl(); /* 10 */
YY_RULE(int) yy_FunctionCall(); /* 9 */
YY_RULE(int) yy_Sum(); /* 8 */
YY_RULE(int) yy_ASSIGN(); /* 7 */
YY_RULE(int) yy_IDENT(); /* 6 */
YY_RULE(int) yy_Decl(); /* 5 */
YY_RULE(int) yy_EOL(); /* 4 */
YY_RULE(int) yy_Expr(); /* 3 */
YY_RULE(int) yy_WS(); /* 2 */
YY_RULE(int) yy_Stmt(); /* 1 */

YY_ACTION(void) yy_1_STRING_LIT(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_STRING_LIT\n"));
   StringLiteral_new_stringLiteral(yytext, nullToken) ;
}
YY_ACTION(void) yy_4_Value(char *yytext, int yyleng)
{
#define i yyval[-1]
  yyprintf((stderr, "do yy_4_Value\n"));
   printf("<parenthesis>\n"); ;
#undef i
}
YY_ACTION(void) yy_3_Value(char *yytext, int yyleng)
{
#define i yyval[-1]
  yyprintf((stderr, "do yy_3_Value\n"));
   printf("<variableAccess> '%s'\n", yytext); ;
#undef i
}
YY_ACTION(void) yy_2_Value(char *yytext, int yyleng)
{
#define i yyval[-1]
  yyprintf((stderr, "do yy_2_Value\n"));
   printf("<stringLiteral \"%s\">\n", yytext); ;
#undef i
}
YY_ACTION(void) yy_1_Value(char *yytext, int yyleng)
{
#define i yyval[-1]
  yyprintf((stderr, "do yy_1_Value\n"));
   printf("<value> '%s'\n", yytext); yy=1 ;
#undef i
}
YY_ACTION(void) yy_4_Product(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_4_Product\n"));
   printf("</product>\n") ;
#undef r
#undef l
}
YY_ACTION(void) yy_3_Product(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_3_Product\n"));
   printf("/ '%s'\n", yytext); ;
#undef r
#undef l
}
YY_ACTION(void) yy_2_Product(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_2_Product\n"));
   printf("* '%s'\n", yytext); ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_Product(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_Product\n"));
   printf("<product> '%s'\n", yytext) ;
#undef r
#undef l
}
YY_ACTION(void) yy_4_Sum(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_4_Sum\n"));
   printf("</sum>\n") ;
#undef r
#undef l
}
YY_ACTION(void) yy_3_Sum(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_3_Sum\n"));
   printf("- '%s'\n", yytext); ;
#undef r
#undef l
}
YY_ACTION(void) yy_2_Sum(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_2_Sum\n"));
   printf("+ '%s'\n", yytext); ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_Sum(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_Sum\n"));
   printf("<sum> '%s'\n", yytext) ;
#undef r
#undef l
}
YY_ACTION(void) yy_2_ExpressionList(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_ExpressionList\n"));
  printf("Got another argument\n");
}
YY_ACTION(void) yy_1_ExpressionList(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_ExpressionList\n"));
   printf("Got first argument\n") ;
}
YY_ACTION(void) yy_2_FunctionCall(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_FunctionCall\n"));
   printf("</functionCall>") ;
}
YY_ACTION(void) yy_1_FunctionCall(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_FunctionCall\n"));
  
                    printf("<functionCall '%s'>\n", yytext);
                    stack_push(FunctionCall_new_funcCall(yytext, nullToken));
                ;
}
YY_ACTION(void) yy_1_Line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_Line\n"));
   printf("</line>\n") ;
}
YY_ACTION(void) yy_2_Body(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_Body\n"));
   printf("</body>\n") ;
}
YY_ACTION(void) yy_1_Body(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_Body\n"));
   printf("<body>\n") ;
}
YY_ACTION(void) yy_2_FunctionDecl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_FunctionDecl\n"));
   printf("</functionDecl>\n") ;
}
YY_ACTION(void) yy_1_FunctionDecl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_FunctionDecl\n"));
  
                    printf("<functionDecl '%s'>\n", yytext);
                    stack_push(FunctionDecl_new_funcDecl(yytext, nullToken));
                ;
}
YY_ACTION(void) yy_1_Stmt(char *yytext, int yyleng)
{
#define d yyval[-1]
#define e yyval[-2]
  yyprintf((stderr, "do yy_1_Stmt\n"));
   printf("error\n"); ;
#undef d
#undef e
}

YY_RULE(int) yy_STRING_LIT()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "STRING_LIT"));  if (!yymatchChar('"')) goto l1;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l1;
  l2:;	
  {  int yypos3= yypos, yythunkpos3= yythunkpos;
  {  int yypos4= yypos, yythunkpos4= yythunkpos;  if (!yymatchChar('"')) goto l4;  goto l3;
  l4:;	  yypos= yypos4; yythunkpos= yythunkpos4;
  }  if (!yymatchDot()) goto l3;  goto l2;
  l3:;	  yypos= yypos3; yythunkpos= yythunkpos3;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l1;  if (!yymatchChar('"')) goto l1;  if (!yy__()) goto l1;  yyDo(yy_1_STRING_LIT, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING_LIT", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING_LIT", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_NUMBER()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "NUMBER"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l5;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l5;
  l6:;	
  {  int yypos7= yypos, yythunkpos7= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l7;  goto l6;
  l7:;	  yypos= yypos7; yythunkpos= yythunkpos7;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l5;  if (!yy__()) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMBER", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMBER", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_DIV()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "DIV"));  if (!yymatchChar('/')) goto l8;  if (!yy__()) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "DIV", yybuf+yypos));
  return 1;
  l8:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DIV", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_TIMES()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "TIMES"));  if (!yymatchChar('*')) goto l9;  if (!yy__()) goto l9;
  yyprintf((stderr, "  ok   %s @ %s\n", "TIMES", yybuf+yypos));
  return 1;
  l9:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TIMES", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Value()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Value"));
  {  int yypos11= yypos, yythunkpos11= yythunkpos;  if (!yy_NUMBER()) goto l12;  yyDo(yySet, -1, 0);  yyDo(yy_1_Value, yybegin, yyend);  goto l11;
  l12:;	  yypos= yypos11; yythunkpos= yythunkpos11;  if (!yy_STRING_LIT()) goto l13;  yyDo(yySet, -1, 0);  yyDo(yy_2_Value, yybegin, yyend);  goto l11;
  l13:;	  yypos= yypos11; yythunkpos= yythunkpos11;  if (!yy_IDENT()) goto l14;  yyDo(yySet, -1, 0);
  {  int yypos15= yypos, yythunkpos15= yythunkpos;  if (!yy_ASSIGN()) goto l15;  goto l14;
  l15:;	  yypos= yypos15; yythunkpos= yythunkpos15;
  }  yyDo(yy_3_Value, yybegin, yyend);  goto l11;
  l14:;	  yypos= yypos11; yythunkpos= yythunkpos11;  if (!yy_OPEN_PAREN()) goto l10;  if (!yy_Expr()) goto l10;  yyDo(yySet, -1, 0);  if (!yy_CLOS_PAREN()) goto l10;  yyDo(yy_4_Value, yybegin, yyend);
  }
  l11:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Value", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l10:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Value", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_MINUS()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "MINUS"));  if (!yymatchChar('-')) goto l16;  if (!yy__()) goto l16;
  yyprintf((stderr, "  ok   %s @ %s\n", "MINUS", yybuf+yypos));
  return 1;
  l16:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MINUS", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_PLUS()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "PLUS"));  if (!yymatchChar('+')) goto l17;  if (!yy__()) goto l17;
  yyprintf((stderr, "  ok   %s @ %s\n", "PLUS", yybuf+yypos));
  return 1;
  l17:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLUS", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Product()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Product"));  if (!yy_Value()) goto l18;  yyDo(yySet, -2, 0);  yyDo(yy_1_Product, yybegin, yyend);
  l19:;	
  {  int yypos20= yypos, yythunkpos20= yythunkpos;
  {  int yypos21= yypos, yythunkpos21= yythunkpos;  if (!yy_TIMES()) goto l22;  if (!yy_Value()) goto l22;  yyDo(yySet, -1, 0);  yyDo(yy_2_Product, yybegin, yyend);  goto l21;
  l22:;	  yypos= yypos21; yythunkpos= yythunkpos21;  if (!yy_DIV()) goto l20;  if (!yy_Value()) goto l20;  yyDo(yySet, -1, 0);  yyDo(yy_3_Product, yybegin, yyend);
  }
  l21:;	  goto l19;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }  yyDo(yy_4_Product, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "Product", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l18:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Product", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_COMMA()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "COMMA"));  if (!yymatchChar(',')) goto l23;  if (!yy__()) goto l23;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMA", yybuf+yypos));
  return 1;
  l23:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMA", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CLOS_PAREN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOS_PAREN"));  if (!yymatchChar(')')) goto l24;  if (!yy__()) goto l24;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOS_PAREN", yybuf+yypos));
  return 1;
  l24:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOS_PAREN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ExpressionList()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ExpressionList"));  if (!yy_Expr()) goto l25;  yyDo(yy_1_ExpressionList, yybegin, yyend);
  l26:;	
  {  int yypos27= yypos, yythunkpos27= yythunkpos;  if (!yy_COMMA()) goto l27;  if (!yy_Expr()) goto l27;  yyDo(yy_2_ExpressionList, yybegin, yyend);  goto l26;
  l27:;	  yypos= yypos27; yythunkpos= yythunkpos27;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "ExpressionList", yybuf+yypos));
  return 1;
  l25:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ExpressionList", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OPEN_PAREN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN_PAREN"));  if (!yymatchChar('(')) goto l28;  if (!yy__()) goto l28;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_PAREN", yybuf+yypos));
  return 1;
  l28:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_PAREN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CLOS_BRACK()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOS_BRACK"));  if (!yymatchChar('}')) goto l29;  if (!yy__()) goto l29;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOS_BRACK", yybuf+yypos));
  return 1;
  l29:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOS_BRACK", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Line"));  if (!yy_WS()) goto l30;
  {  int yypos31= yypos, yythunkpos31= yythunkpos;  if (!yy_EOL()) goto l31;  goto l30;
  l31:;	  yypos= yypos31; yythunkpos= yythunkpos31;
  }  if (!yy_Expr()) goto l30;
  l32:;	
  {  int yypos33= yypos, yythunkpos33= yythunkpos;  if (!yy_EOL()) goto l33;  goto l32;
  l33:;	  yypos= yypos33; yythunkpos= yythunkpos33;
  }  yyDo(yy_1_Line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "Line", yybuf+yypos));
  return 1;
  l30:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OPEN_BRACK()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN_BRACK"));  if (!yymatchChar('{')) goto l34;  if (!yy__()) goto l34;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_BRACK", yybuf+yypos));
  return 1;
  l34:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_BRACK", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Body"));  if (!yy_OPEN_BRACK()) goto l35;  yyDo(yy_1_Body, yybegin, yyend);
  l36:;	
  {  int yypos37= yypos, yythunkpos37= yythunkpos;  if (!yy_EOL()) goto l37;  goto l36;
  l37:;	  yypos= yypos37; yythunkpos= yythunkpos37;
  }
  l38:;	
  {  int yypos39= yypos, yythunkpos39= yythunkpos;  if (!yy_Line()) goto l39;  goto l38;
  l39:;	  yypos= yypos39; yythunkpos= yythunkpos39;
  }  if (!yy_CLOS_BRACK()) goto l35;  yyDo(yy_2_Body, yybegin, yyend);  if (!yy__()) goto l35;
  yyprintf((stderr, "  ok   %s @ %s\n", "Body", yybuf+yypos));
  return 1;
  l35:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Body", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{
  yyprintf((stderr, "%s\n", "_"));
  l41:;	
  {  int yypos42= yypos, yythunkpos42= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l42;  goto l41;
  l42:;	  yypos= yypos42; yythunkpos= yythunkpos42;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_COLON()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "COLON"));  if (!yymatchChar(':')) goto l43;  if (!yy__()) goto l43;
  yyprintf((stderr, "  ok   %s @ %s\n", "COLON", yybuf+yypos));
  return 1;
  l43:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COLON", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_FunctionDecl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "FunctionDecl"));  if (!yy_IDENT()) goto l44;  yyDo(yy_1_FunctionDecl, yybegin, yyend);  if (!yy_COLON()) goto l44;  if (!yymatchString("func")) goto l44;  if (!yy__()) goto l44;
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy_Body()) goto l45;  goto l46;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }
  l46:;	  yyDo(yy_2_FunctionDecl, yybegin, yyend);  if (!yy__()) goto l44;
  yyprintf((stderr, "  ok   %s @ %s\n", "FunctionDecl", yybuf+yypos));
  return 1;
  l44:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FunctionDecl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_FunctionCall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "FunctionCall"));  if (!yy_IDENT()) goto l47;  yyDo(yy_1_FunctionCall, yybegin, yyend);  if (!yy_OPEN_PAREN()) goto l47;
  {  int yypos48= yypos, yythunkpos48= yythunkpos;  if (!yy_ExpressionList()) goto l48;  goto l49;
  l48:;	  yypos= yypos48; yythunkpos= yythunkpos48;
  }
  l49:;	  if (!yy_CLOS_PAREN()) goto l47;  yyDo(yy_2_FunctionCall, yybegin, yyend);  if (!yy__()) goto l47;
  yyprintf((stderr, "  ok   %s @ %s\n", "FunctionCall", yybuf+yypos));
  return 1;
  l47:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FunctionCall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Sum()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Sum"));  if (!yy_Product()) goto l50;  yyDo(yySet, -2, 0);  yyDo(yy_1_Sum, yybegin, yyend);
  l51:;	
  {  int yypos52= yypos, yythunkpos52= yythunkpos;
  {  int yypos53= yypos, yythunkpos53= yythunkpos;  if (!yy_PLUS()) goto l54;  if (!yy_Product()) goto l54;  yyDo(yySet, -1, 0);  yyDo(yy_2_Sum, yybegin, yyend);  goto l53;
  l54:;	  yypos= yypos53; yythunkpos= yythunkpos53;  if (!yy_MINUS()) goto l52;  if (!yy_Product()) goto l52;  yyDo(yySet, -1, 0);  yyDo(yy_3_Sum, yybegin, yyend);
  }
  l53:;	  goto l51;
  l52:;	  yypos= yypos52; yythunkpos= yythunkpos52;
  }  yyDo(yy_4_Sum, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "Sum", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l50:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Sum", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ASSIGN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ASSIGN"));  if (!yymatchChar('=')) goto l55;  if (!yy__()) goto l55;
  yyprintf((stderr, "  ok   %s @ %s\n", "ASSIGN", yybuf+yypos));
  return 1;
  l55:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ASSIGN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_IDENT()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "IDENT"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l56;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l56;
  l57:;	
  {  int yypos58= yypos, yythunkpos58= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l58;  goto l57;
  l58:;	  yypos= yypos58; yythunkpos= yythunkpos58;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l56;  if (!yy__()) goto l56;
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT", yybuf+yypos));
  return 1;
  l56:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Decl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Decl"));  if (!yy_FunctionDecl()) goto l59;
  yyprintf((stderr, "  ok   %s @ %s\n", "Decl", yybuf+yypos));
  return 1;
  l59:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Decl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_EOL()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos61= yypos, yythunkpos61= yythunkpos;  if (!yymatchChar('\n')) goto l62;  goto l61;
  l62:;	  yypos= yypos61; yythunkpos= yythunkpos61;  if (!yymatchString("\r\n")) goto l63;  goto l61;
  l63:;	  yypos= yypos61; yythunkpos= yythunkpos61;  if (!yymatchChar('\r')) goto l64;  goto l61;
  l64:;	  yypos= yypos61; yythunkpos= yythunkpos61;  if (!yymatchChar(';')) goto l60;
  }
  l61:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yybuf+yypos));
  return 1;
  l60:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "Expr"));
  {  int yypos66= yypos, yythunkpos66= yythunkpos;  if (!yy_IDENT()) goto l67;  yyDo(yySet, 0, 0);  if (!yy_ASSIGN()) goto l67;  if (!yy_Sum()) goto l67;  yyDo(yySet, 0, 0);  goto l66;
  l67:;	  yypos= yypos66; yythunkpos= yythunkpos66;  if (!yy_FunctionCall()) goto l68;  yyDo(yySet, 0, 0);  goto l66;
  l68:;	  yypos= yypos66; yythunkpos= yythunkpos66;  if (!yy_Sum()) goto l65;  yyDo(yySet, 0, 0);
  }
  l66:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Expr", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l65:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_WS()
{
  yyprintf((stderr, "%s\n", "WS"));
  l70:;	
  {  int yypos71= yypos, yythunkpos71= yythunkpos;
  {  int yypos72= yypos, yythunkpos72= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l73;  goto l72;
  l73:;	  yypos= yypos72; yythunkpos= yythunkpos72;  if (!yy_EOL()) goto l71;
  }
  l72:;	  goto l70;
  l71:;	  yypos= yypos71; yythunkpos= yythunkpos71;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "WS", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_Stmt()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Stmt"));
  {  int yypos75= yypos, yythunkpos75= yythunkpos;  if (!yy_WS()) goto l76;  if (!yy_Expr()) goto l76;  yyDo(yySet, -2, 0);  if (!yy_EOL()) goto l76;  goto l75;
  l76:;	  yypos= yypos75; yythunkpos= yythunkpos75;  if (!yy_WS()) goto l77;  if (!yy_Decl()) goto l77;  yyDo(yySet, -1, 0);  if (!yy_EOL()) goto l77;  goto l75;
  l77:;	  yypos= yypos75; yythunkpos= yythunkpos75;
  l78:;	
  {  int yypos79= yypos, yythunkpos79= yythunkpos;
  {  int yypos80= yypos, yythunkpos80= yythunkpos;  if (!yy_EOL()) goto l80;  goto l79;
  l80:;	  yypos= yypos80; yythunkpos= yythunkpos80;
  }  if (!yymatchDot()) goto l79;  goto l78;
  l79:;	  yypos= yypos79; yythunkpos= yythunkpos79;
  }  if (!yy_EOL()) goto l74;  yyDo(yy_1_Stmt, yybegin, yyend);
  }
  l75:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Stmt", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l74:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Stmt", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_Stmt);
}

#endif


int Parser_parse() {
  while (yyparse()) {}
  
  return 0;
}

