/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 40

#include <stdio.h>

/* ooc/rock imports */
#include <sdk/lang/BasicTypes-fwd.h>
#include <sdk/io/FileReader.h>

#include <source/rock/frontend/CommandLine-fwd.h>
#include <source/rock/middle/Parenthesis-fwd.h>
#include <source/rock/middle/Type-fwd.h>
#include <source/rock/middle/Line-fwd.h>
#include <source/rock/middle/Node-fwd.h>
#include <source/rock/middle/StringLiteral-fwd.h>
#include <source/rock/middle/VariableAccess-fwd.h>
#include <source/rock/middle/IntLiteral-fwd.h>
#include <source/rock/middle/BinaryOp.h> // tight dependency: we use static members
#include <source/rock/middle/FunctionCall-fwd.h>
#include <source/rock/middle/FunctionDecl-fwd.h>
#include <source/rock/middle/CoverDecl-fwd.h>

#define YYSTYPE struct _rock_middle__Node*

typedef char *String;
typedef struct _lang__Object *Object;
typedef struct _rock_middle__Node *Node;
typedef struct _rock_middle__Type *Type;
typedef struct _rock_middle__Statement *Statement;
typedef struct _rock_middle__CoverDecl *CoverDecl;
typedef struct _rock_middle__ClassDecl *ClassDecl;
typedef struct _rock_middle__Expression *Expression;
typedef struct _rock_middle__OpTypesClass *OpTypesClass;

// uncomment to enable leg's finicky debug output
//#define YY_DEBUG 1

/* Current line number */
static int yylineno;

/* Path of the file we're parsing. */
static char* path;
 
/* The stream we're reading from. */
static struct _io__FileReader *stream;

/* Send input to yyparse from codebuf instead of stdin */
#define YY_INPUT(buf, result, max_size) {        \
    result = FileReader_read(stream, buf, 0, max_size);     \
    static int doneNewlineHack = 0;              \
    if(result == 0 && doneNewlineHack == 0) {    \
        doneNewlineHack = 1;                     \
        char last = buf[strlen(buf) - 1];        \
        if(last != '\n') {                       \
            (*buf) = '\n';                       \
            result = 1;                          \
        }                                        \
    }                                            \
}


#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_STRING_LIT(); /* 40 */
YY_RULE(int) yy_NUMBER(); /* 39 */
YY_RULE(int) yy_DIV(); /* 38 */
YY_RULE(int) yy_TIMES(); /* 37 */
YY_RULE(int) yy_Value(); /* 36 */
YY_RULE(int) yy_MINUS(); /* 35 */
YY_RULE(int) yy_PLUS(); /* 34 */
YY_RULE(int) yy_Product(); /* 33 */
YY_RULE(int) yy_COMMA(); /* 32 */
YY_RULE(int) yy_CLOS_PAREN(); /* 31 */
YY_RULE(int) yy_ExpressionList(); /* 30 */
YY_RULE(int) yy_OPEN_PAREN(); /* 29 */
YY_RULE(int) yy_ASSIGN(); /* 28 */
YY_RULE(int) yy_VariableAccess(); /* 27 */
YY_RULE(int) yy_CommentMultiLine(); /* 26 */
YY_RULE(int) yy_CommentLine(); /* 25 */
YY_RULE(int) yy_Type(); /* 24 */
YY_RULE(int) yy_FromCoverDecl(); /* 23 */
YY_RULE(int) yy_TypeDeclBody(); /* 22 */
YY_RULE(int) yy_ClassDecl(); /* 21 */
YY_RULE(int) yy_CoverDecl(); /* 20 */
YY_RULE(int) yy_CLOS_BRACK(); /* 19 */
YY_RULE(int) yy_Line(); /* 18 */
YY_RULE(int) yy_OPEN_BRACK(); /* 17 */
YY_RULE(int) yy_Body(); /* 16 */
YY_RULE(int) yy__(); /* 15 */
YY_RULE(int) yy_COLON(); /* 14 */
YY_RULE(int) yy_IDENT(); /* 13 */
YY_RULE(int) yy_FunctionDecl(); /* 12 */
YY_RULE(int) yy_TypeDecl(); /* 11 */
YY_RULE(int) yy_Comment(); /* 10 */
YY_RULE(int) yy_Sum(); /* 9 */
YY_RULE(int) yy_FunctionCall(); /* 8 */
YY_RULE(int) yy_VariableDecl(); /* 7 */
YY_RULE(int) yy_Assignment(); /* 6 */
YY_RULE(int) yy_Expr(); /* 5 */
YY_RULE(int) yy_EOL(); /* 4 */
YY_RULE(int) yy_Decl(); /* 3 */
YY_RULE(int) yy_WS(); /* 2 */
YY_RULE(int) yy_Stmt(); /* 1 */

YY_ACTION(void) yy_1_EOL(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_EOL\n"));
   yylineno++ ;
}
YY_ACTION(void) yy_1_IDENT(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_IDENT\n"));
   yy=(Node) String_clone(yytext) ;
}
YY_ACTION(void) yy_1_STRING_LIT(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_STRING_LIT\n"));
   yy=(Node) StringLiteral_new_stringLiteral(String_clone(yytext), nullToken); ;
}
YY_ACTION(void) yy_1_NUMBER(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_NUMBER\n"));
   yy=(Node) IntLiteral_new_intLiteral(atoll(yytext), nullToken); ;
}
YY_ACTION(void) yy_1_Value(char *yytext, int yyleng)
{
#define inner yyval[-1]
#define i yyval[-2]
  yyprintf((stderr, "do yy_1_Value\n"));
  
            yy=(Node) Parenthesis_new_parenthesis((Expression) inner, nullToken)
        ;
#undef inner
#undef i
}
YY_ACTION(void) yy_2_Product(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_2_Product\n"));
  
                    yy=(Node) BinaryOp_new_binaryOp((Expression) l, (Expression) r,
                        ((OpTypesClass) OpTypes_class())->div, nullToken);
                ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_Product(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_Product\n"));
  
                    yy=(Node) BinaryOp_new_binaryOp((Expression) l, (Expression) r,
                        ((OpTypesClass) OpTypes_class())->mul, nullToken);
                ;
#undef r
#undef l
}
YY_ACTION(void) yy_2_Sum(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_2_Sum\n"));
  
                    yy=(Node) BinaryOp_new_binaryOp((Expression) l, (Expression) r,
                        ((OpTypesClass) OpTypes_class())->sub, nullToken);
                ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_Sum(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_Sum\n"));
  
                    yy=(Node) BinaryOp_new_binaryOp((Expression) l, (Expression) r,
                        ((OpTypesClass) OpTypes_class())->add, nullToken);
                ;
#undef r
#undef l
}
YY_ACTION(void) yy_2_ExpressionList(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_ExpressionList\n"));
   stack_add(yy) ;
}
YY_ACTION(void) yy_1_ExpressionList(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_ExpressionList\n"));
   stack_add(yy) ;
}
YY_ACTION(void) yy_2_FunctionCall(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_FunctionCall\n"));
  
        yy= (Node) stack_pop(FunctionCall_class());
    ;
}
YY_ACTION(void) yy_1_FunctionCall(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_FunctionCall\n"));
  
        stack_push((Node) FunctionCall_new_funcCall(String_clone(yytext), nullToken));
    ;
}
YY_ACTION(void) yy_2_VariableAccess(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_VariableAccess\n"));
   printf("Got member access! %s\n", yytext); ;
}
YY_ACTION(void) yy_1_VariableAccess(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_VariableAccess\n"));
   yy=(Node) VariableAccess_new_variableAccess(String_clone(yytext), nullToken); ;
}
YY_ACTION(void) yy_1_Assignment(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_Assignment\n"));
  
        printf("Parsed an assignment, l is a %s\n", ((Object) l)->class->name);
        yy=(Node) BinaryOp_new_binaryOp((Expression) l, (Expression) r, ((OpTypesClass) OpTypes_class())->ass, nullToken);
    ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_Type(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_Type\n"));
   yy=(Node) BaseType_new_baseType(String_clone(yytext), nullToken) ;
}
YY_ACTION(void) yy_1_VariableDecl(char *yytext, int yyleng)
{
#define type yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_VariableDecl\n"));
  
        yy=(Node) VariableDecl_new_vDecl((Type) type, (String) name, nullToken);
    ;
#undef type
#undef name
}
YY_ACTION(void) yy_2_ClassDecl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_ClassDecl\n"));
  
        stack_pop(ClassDecl_class())
    ;
}
YY_ACTION(void) yy_1_ClassDecl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_ClassDecl\n"));
  
        stack_push((Node) ClassDecl_new_classDecl(String_clone(yytext), NULL, nullToken))
    ;
}
YY_ACTION(void) yy_3_FromCoverDecl(char *yytext, int yyleng)
{
#define t yyval[-1]
  yyprintf((stderr, "do yy_3_FromCoverDecl\n"));
  
        stack_pop(CoverDecl_class())
    ;
#undef t
}
YY_ACTION(void) yy_2_FromCoverDecl(char *yytext, int yyleng)
{
#define t yyval[-1]
  yyprintf((stderr, "do yy_2_FromCoverDecl\n"));
   CoverDecl_setFromType((CoverDecl) stack_peek(), (Type) t); ;
#undef t
}
YY_ACTION(void) yy_1_FromCoverDecl(char *yytext, int yyleng)
{
#define t yyval[-1]
  yyprintf((stderr, "do yy_1_FromCoverDecl\n"));
  
        stack_push((Node) CoverDecl_new_coverDecl(String_clone(yytext), NULL, nullToken))
    ;
#undef t
}
YY_ACTION(void) yy_2_TypeDeclBody(char *yytext, int yyleng)
{
#define vDecl yyval[-1]
#define fDecl yyval[-2]
  yyprintf((stderr, "do yy_2_TypeDeclBody\n"));
   stack_add(vDecl); ;
#undef vDecl
#undef fDecl
}
YY_ACTION(void) yy_1_TypeDeclBody(char *yytext, int yyleng)
{
#define vDecl yyval[-1]
#define fDecl yyval[-2]
  yyprintf((stderr, "do yy_1_TypeDeclBody\n"));
   stack_add(fDecl); ;
#undef vDecl
#undef fDecl
}
YY_ACTION(void) yy_1_Line(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_Line\n"));
  
            stack_add((Node) Line_new_line((Statement) yy));
        ;
#undef e
}
YY_ACTION(void) yy_2_FunctionDecl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_FunctionDecl\n"));
  
        yy=(Node) stack_pop(FunctionDecl_class())
    ;
}
YY_ACTION(void) yy_1_FunctionDecl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_FunctionDecl\n"));
  
        yy=(Node) FunctionDecl_new_funcDecl(String_clone(yytext), nullToken);
        stack_push(yy);
    ;
}
YY_ACTION(void) yy_1_Stmt(char *yytext, int yyleng)
{
#define e yyval[-1]
#define d yyval[-2]
  yyprintf((stderr, "do yy_1_Stmt\n"));
  
            printf("error at line %d: unexpected input '%s'\n", yylineno, yytext);
            exit(1);
        ;
#undef e
#undef d
}

YY_RULE(int) yy_STRING_LIT()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "STRING_LIT"));  if (!yymatchChar('"')) goto l1;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l1;
  l2:;	
  {  int yypos3= yypos, yythunkpos3= yythunkpos;
  {  int yypos4= yypos, yythunkpos4= yythunkpos;  if (!yymatchChar('"')) goto l4;  goto l3;
  l4:;	  yypos= yypos4; yythunkpos= yythunkpos4;
  }  if (!yymatchDot()) goto l3;  goto l2;
  l3:;	  yypos= yypos3; yythunkpos= yythunkpos3;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l1;  if (!yymatchChar('"')) goto l1;  if (!yy__()) goto l1;  yyDo(yy_1_STRING_LIT, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING_LIT", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING_LIT", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_NUMBER()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "NUMBER"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l5;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l5;
  l6:;	
  {  int yypos7= yypos, yythunkpos7= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l7;  goto l6;
  l7:;	  yypos= yypos7; yythunkpos= yythunkpos7;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l5;  if (!yy__()) goto l5;  yyDo(yy_1_NUMBER, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMBER", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMBER", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_DIV()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "DIV"));  if (!yymatchChar('/')) goto l8;  if (!yy__()) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "DIV", yybuf+yypos));
  return 1;
  l8:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DIV", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_TIMES()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "TIMES"));  if (!yymatchChar('*')) goto l9;  if (!yy__()) goto l9;
  yyprintf((stderr, "  ok   %s @ %s\n", "TIMES", yybuf+yypos));
  return 1;
  l9:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TIMES", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Value()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Value"));
  {  int yypos11= yypos, yythunkpos11= yythunkpos;  if (!yy_NUMBER()) goto l12;  yyDo(yySet, -2, 0);  goto l11;
  l12:;	  yypos= yypos11; yythunkpos= yythunkpos11;  if (!yy_STRING_LIT()) goto l13;  yyDo(yySet, -2, 0);  goto l11;
  l13:;	  yypos= yypos11; yythunkpos= yythunkpos11;  if (!yy_VariableAccess()) goto l14;
  {  int yypos15= yypos, yythunkpos15= yythunkpos;  if (!yy_ASSIGN()) goto l15;  goto l14;
  l15:;	  yypos= yypos15; yythunkpos= yythunkpos15;
  }  goto l11;
  l14:;	  yypos= yypos11; yythunkpos= yythunkpos11;  if (!yy_OPEN_PAREN()) goto l10;  if (!yy_Expr()) goto l10;  yyDo(yySet, -1, 0);  if (!yy_CLOS_PAREN()) goto l10;  yyDo(yy_1_Value, yybegin, yyend);
  }
  l11:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Value", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l10:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Value", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_MINUS()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "MINUS"));  if (!yymatchChar('-')) goto l16;  if (!yy__()) goto l16;
  yyprintf((stderr, "  ok   %s @ %s\n", "MINUS", yybuf+yypos));
  return 1;
  l16:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MINUS", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_PLUS()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "PLUS"));  if (!yymatchChar('+')) goto l17;  if (!yy__()) goto l17;
  yyprintf((stderr, "  ok   %s @ %s\n", "PLUS", yybuf+yypos));
  return 1;
  l17:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLUS", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Product()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Product"));  if (!yy_Value()) goto l18;  yyDo(yySet, -2, 0);
  l19:;	
  {  int yypos20= yypos, yythunkpos20= yythunkpos;
  {  int yypos21= yypos, yythunkpos21= yythunkpos;  if (!yy_TIMES()) goto l22;  if (!yy_Value()) goto l22;  yyDo(yySet, -1, 0);  yyDo(yy_1_Product, yybegin, yyend);  goto l21;
  l22:;	  yypos= yypos21; yythunkpos= yythunkpos21;  if (!yy_DIV()) goto l20;  if (!yy_Value()) goto l20;  yyDo(yySet, -1, 0);  yyDo(yy_2_Product, yybegin, yyend);
  }
  l21:;	  goto l19;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Product", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l18:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Product", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_COMMA()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "COMMA"));  if (!yymatchChar(',')) goto l23;  if (!yy__()) goto l23;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMA", yybuf+yypos));
  return 1;
  l23:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMA", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CLOS_PAREN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOS_PAREN"));  if (!yymatchChar(')')) goto l24;  if (!yy__()) goto l24;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOS_PAREN", yybuf+yypos));
  return 1;
  l24:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOS_PAREN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ExpressionList()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ExpressionList"));  if (!yy_Expr()) goto l25;  yyDo(yy_1_ExpressionList, yybegin, yyend);
  l26:;	
  {  int yypos27= yypos, yythunkpos27= yythunkpos;  if (!yy_COMMA()) goto l27;  if (!yy_Expr()) goto l27;  yyDo(yy_2_ExpressionList, yybegin, yyend);  goto l26;
  l27:;	  yypos= yypos27; yythunkpos= yythunkpos27;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "ExpressionList", yybuf+yypos));
  return 1;
  l25:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ExpressionList", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OPEN_PAREN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN_PAREN"));  if (!yymatchChar('(')) goto l28;  if (!yy__()) goto l28;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_PAREN", yybuf+yypos));
  return 1;
  l28:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_PAREN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ASSIGN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ASSIGN"));  if (!yymatchChar('=')) goto l29;  if (!yy__()) goto l29;
  yyprintf((stderr, "  ok   %s @ %s\n", "ASSIGN", yybuf+yypos));
  return 1;
  l29:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ASSIGN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_VariableAccess()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "VariableAccess"));  if (!yy_IDENT()) goto l30;  yyDo(yy_1_VariableAccess, yybegin, yyend);
  l31:;	
  {  int yypos32= yypos, yythunkpos32= yythunkpos;  if (!yy__()) goto l32;  if (!yy_IDENT()) goto l32;  yyDo(yy_2_VariableAccess, yybegin, yyend);  goto l31;
  l32:;	  yypos= yypos32; yythunkpos= yythunkpos32;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "VariableAccess", yybuf+yypos));
  return 1;
  l30:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VariableAccess", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CommentMultiLine()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CommentMultiLine"));  if (!yymatchString("/*")) goto l33;
  l34:;	
  {  int yypos35= yypos, yythunkpos35= yythunkpos;
  {  int yypos36= yypos, yythunkpos36= yythunkpos;  if (!yymatchString("*/")) goto l36;  goto l35;
  l36:;	  yypos= yypos36; yythunkpos= yythunkpos36;
  }  if (!yymatchDot()) goto l35;  goto l34;
  l35:;	  yypos= yypos35; yythunkpos= yythunkpos35;
  }  if (!yymatchString("*/")) goto l33;
  yyprintf((stderr, "  ok   %s @ %s\n", "CommentMultiLine", yybuf+yypos));
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CommentMultiLine", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CommentLine()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CommentLine"));  if (!yymatchString("//")) goto l37;
  l38:;	
  {  int yypos39= yypos, yythunkpos39= yythunkpos;
  {  int yypos40= yypos, yythunkpos40= yythunkpos;  if (!yy_EOL()) goto l40;  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }  if (!yymatchDot()) goto l39;  goto l38;
  l39:;	  yypos= yypos39; yythunkpos= yythunkpos39;
  }  if (!yy_EOL()) goto l37;
  yyprintf((stderr, "  ok   %s @ %s\n", "CommentLine", yybuf+yypos));
  return 1;
  l37:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CommentLine", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Type()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Type"));  if (!yy_IDENT()) goto l41;  yyDo(yy_1_Type, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "Type", yybuf+yypos));
  return 1;
  l41:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Type", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_FromCoverDecl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "FromCoverDecl"));  if (!yy_IDENT()) goto l42;  yyDo(yy_1_FromCoverDecl, yybegin, yyend);  if (!yy__()) goto l42;  if (!yy_COLON()) goto l42;  if (!yymatchString("cover")) goto l42;  if (!yy__()) goto l42;  if (!yymatchString("from")) goto l42;  if (!yy__()) goto l42;  if (!yy_Type()) goto l42;  yyDo(yySet, -1, 0);  yyDo(yy_2_FromCoverDecl, yybegin, yyend);  if (!yy__()) goto l42;  if (!yy_EOL()) goto l42;  if (!yy__()) goto l42;  yyDo(yy_3_FromCoverDecl, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "FromCoverDecl", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l42:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FromCoverDecl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_TypeDeclBody()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "TypeDeclBody"));
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;
  {  int yypos46= yypos, yythunkpos46= yythunkpos;  if (!yy_WS()) goto l47;  if (!yy_FunctionDecl()) goto l47;  yyDo(yySet, -2, 0);  yyDo(yy_1_TypeDeclBody, yybegin, yyend);  goto l46;
  l47:;	  yypos= yypos46; yythunkpos= yythunkpos46;  if (!yy_WS()) goto l48;  if (!yy_VariableDecl()) goto l48;  yyDo(yySet, -1, 0);  yyDo(yy_2_TypeDeclBody, yybegin, yyend);  goto l46;
  l48:;	  yypos= yypos46; yythunkpos= yythunkpos46;  if (!yy_WS()) goto l45;  if (!yy_Comment()) goto l45;
  }
  l46:;	  goto l44;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }  if (!yy_WS()) goto l43;
  yyprintf((stderr, "  ok   %s @ %s\n", "TypeDeclBody", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l43:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TypeDeclBody", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ClassDecl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ClassDecl"));  if (!yy_IDENT()) goto l49;  yyDo(yy_1_ClassDecl, yybegin, yyend);  if (!yy__()) goto l49;  if (!yy_COLON()) goto l49;  if (!yymatchString("class")) goto l49;  if (!yy__()) goto l49;  if (!yy_OPEN_BRACK()) goto l49;
  {  int yypos50= yypos, yythunkpos50= yythunkpos;  if (!yy_TypeDeclBody()) goto l50;  goto l51;
  l50:;	  yypos= yypos50; yythunkpos= yythunkpos50;
  }
  l51:;	  if (!yy_WS()) goto l49;  if (!yy_CLOS_BRACK()) goto l49;  if (!yy__()) goto l49;  yyDo(yy_2_ClassDecl, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "ClassDecl", yybuf+yypos));
  return 1;
  l49:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ClassDecl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CoverDecl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CoverDecl"));  if (!yy_FromCoverDecl()) goto l52;
  yyprintf((stderr, "  ok   %s @ %s\n", "CoverDecl", yybuf+yypos));
  return 1;
  l52:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CoverDecl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CLOS_BRACK()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOS_BRACK"));  if (!yymatchChar('}')) goto l53;  if (!yy__()) goto l53;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOS_BRACK", yybuf+yypos));
  return 1;
  l53:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOS_BRACK", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Line"));
  {  int yypos55= yypos, yythunkpos55= yythunkpos;  if (!yy_WS()) goto l56;
  {  int yypos57= yypos, yythunkpos57= yythunkpos;  if (!yy_EOL()) goto l57;  goto l56;
  l57:;	  yypos= yypos57; yythunkpos= yythunkpos57;
  }  if (!yy_Expr()) goto l56;  yyDo(yySet, -1, 0);  if (!yy_EOL()) goto l56;  if (!yy_WS()) goto l56;  yyDo(yy_1_Line, yybegin, yyend);  goto l55;
  l56:;	  yypos= yypos55; yythunkpos= yythunkpos55;  if (!yy_Comment()) goto l54;
  }
  l55:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Line", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l54:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OPEN_BRACK()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN_BRACK"));  if (!yymatchChar('{')) goto l58;  if (!yy__()) goto l58;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_BRACK", yybuf+yypos));
  return 1;
  l58:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_BRACK", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Body"));  if (!yy_OPEN_BRACK()) goto l59;  if (!yy_WS()) goto l59;
  l60:;	
  {  int yypos61= yypos, yythunkpos61= yythunkpos;  if (!yy_Line()) goto l61;  goto l60;
  l61:;	  yypos= yypos61; yythunkpos= yythunkpos61;
  }  if (!yy_WS()) goto l59;  if (!yy_CLOS_BRACK()) goto l59;  if (!yy__()) goto l59;
  yyprintf((stderr, "  ok   %s @ %s\n", "Body", yybuf+yypos));
  return 1;
  l59:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Body", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{
  yyprintf((stderr, "%s\n", "_"));
  l63:;	
  {  int yypos64= yypos, yythunkpos64= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l64;  goto l63;
  l64:;	  yypos= yypos64; yythunkpos= yythunkpos64;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_COLON()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "COLON"));  if (!yymatchChar(':')) goto l65;  if (!yy__()) goto l65;
  yyprintf((stderr, "  ok   %s @ %s\n", "COLON", yybuf+yypos));
  return 1;
  l65:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COLON", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_IDENT()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "IDENT"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l66;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l66;
  l67:;	
  {  int yypos68= yypos, yythunkpos68= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l68;  goto l67;
  l68:;	  yypos= yypos68; yythunkpos= yythunkpos68;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l66;  if (!yy__()) goto l66;  yyDo(yy_1_IDENT, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT", yybuf+yypos));
  return 1;
  l66:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_FunctionDecl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "FunctionDecl"));  if (!yy_IDENT()) goto l69;  yyDo(yy_1_FunctionDecl, yybegin, yyend);  if (!yy_COLON()) goto l69;  if (!yymatchString("func")) goto l69;  if (!yy__()) goto l69;
  {  int yypos70= yypos, yythunkpos70= yythunkpos;  if (!yy_Body()) goto l70;  goto l71;
  l70:;	  yypos= yypos70; yythunkpos= yythunkpos70;
  }
  l71:;	  if (!yy__()) goto l69;  yyDo(yy_2_FunctionDecl, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "FunctionDecl", yybuf+yypos));
  return 1;
  l69:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FunctionDecl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_TypeDecl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "TypeDecl"));
  {  int yypos73= yypos, yythunkpos73= yythunkpos;  if (!yy_CoverDecl()) goto l74;  goto l73;
  l74:;	  yypos= yypos73; yythunkpos= yythunkpos73;  if (!yy_ClassDecl()) goto l72;
  }
  l73:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "TypeDecl", yybuf+yypos));
  return 1;
  l72:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TypeDecl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Comment()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Comment"));
  {  int yypos76= yypos, yythunkpos76= yythunkpos;  if (!yy_CommentLine()) goto l77;  goto l76;
  l77:;	  yypos= yypos76; yythunkpos= yythunkpos76;  if (!yy_CommentMultiLine()) goto l75;
  }
  l76:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Comment", yybuf+yypos));
  return 1;
  l75:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Comment", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Sum()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Sum"));  if (!yy_Product()) goto l78;  yyDo(yySet, -2, 0);
  l79:;	
  {  int yypos80= yypos, yythunkpos80= yythunkpos;
  {  int yypos81= yypos, yythunkpos81= yythunkpos;  if (!yy_PLUS()) goto l82;  if (!yy_Product()) goto l82;  yyDo(yySet, -1, 0);  yyDo(yy_1_Sum, yybegin, yyend);  goto l81;
  l82:;	  yypos= yypos81; yythunkpos= yythunkpos81;  if (!yy_MINUS()) goto l80;  if (!yy_Product()) goto l80;  yyDo(yySet, -1, 0);  yyDo(yy_2_Sum, yybegin, yyend);
  }
  l81:;	  goto l79;
  l80:;	  yypos= yypos80; yythunkpos= yythunkpos80;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Sum", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l78:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Sum", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_FunctionCall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "FunctionCall"));  if (!yy_IDENT()) goto l83;  yyDo(yy_1_FunctionCall, yybegin, yyend);  if (!yy_OPEN_PAREN()) goto l83;
  {  int yypos84= yypos, yythunkpos84= yythunkpos;  if (!yy_ExpressionList()) goto l84;  goto l85;
  l84:;	  yypos= yypos84; yythunkpos= yythunkpos84;
  }
  l85:;	  if (!yy_CLOS_PAREN()) goto l83;  if (!yy__()) goto l83;  yyDo(yy_2_FunctionCall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "FunctionCall", yybuf+yypos));
  return 1;
  l83:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FunctionCall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_VariableDecl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "VariableDecl"));  if (!yy_IDENT()) goto l86;  yyDo(yySet, -2, 0);  if (!yy__()) goto l86;  if (!yy_COLON()) goto l86;  if (!yy__()) goto l86;  if (!yy_Type()) goto l86;  yyDo(yySet, -1, 0);  if (!yy__()) goto l86;  yyDo(yy_1_VariableDecl, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "VariableDecl", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l86:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VariableDecl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Assignment()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Assignment"));  if (!yy_VariableAccess()) goto l87;  yyDo(yySet, -2, 0);  if (!yy_ASSIGN()) goto l87;  if (!yy_Expr()) goto l87;  yyDo(yySet, -1, 0);  if (!yy__()) goto l87;  yyDo(yy_1_Assignment, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "Assignment", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l87:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Assignment", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Expr"));
  {  int yypos89= yypos, yythunkpos89= yythunkpos;  if (!yy_Assignment()) goto l90;  goto l89;
  l90:;	  yypos= yypos89; yythunkpos= yythunkpos89;  if (!yy_VariableDecl()) goto l91;  goto l89;
  l91:;	  yypos= yypos89; yythunkpos= yythunkpos89;  if (!yy_FunctionCall()) goto l92;  goto l89;
  l92:;	  yypos= yypos89; yythunkpos= yythunkpos89;  if (!yy_Sum()) goto l93;  goto l89;
  l93:;	  yypos= yypos89; yythunkpos= yythunkpos89;  if (!yy_WS()) goto l88;  if (!yy_Comment()) goto l88;  if (!yy_WS()) goto l88;  if (!yy_Expr()) goto l88;
  }
  l89:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Expr", yybuf+yypos));
  return 1;
  l88:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_EOL()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos95= yypos, yythunkpos95= yythunkpos;
  {  int yypos97= yypos, yythunkpos97= yythunkpos;  if (!yymatchChar('\n')) goto l98;  goto l97;
  l98:;	  yypos= yypos97; yythunkpos= yythunkpos97;  if (!yymatchString("\r\n")) goto l99;  goto l97;
  l99:;	  yypos= yypos97; yythunkpos= yythunkpos97;  if (!yymatchChar('\r')) goto l96;
  }
  l97:;	  yyDo(yy_1_EOL, yybegin, yyend);  goto l95;
  l96:;	  yypos= yypos95; yythunkpos= yythunkpos95;  if (!yymatchChar(';')) goto l94;
  }
  l95:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yybuf+yypos));
  return 1;
  l94:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Decl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Decl"));
  {  int yypos101= yypos, yythunkpos101= yythunkpos;  if (!yy_TypeDecl()) goto l102;  goto l101;
  l102:;	  yypos= yypos101; yythunkpos= yythunkpos101;  if (!yy_FunctionDecl()) goto l103;  goto l101;
  l103:;	  yypos= yypos101; yythunkpos= yythunkpos101;  if (!yy_VariableDecl()) goto l100;
  }
  l101:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Decl", yybuf+yypos));
  return 1;
  l100:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Decl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_WS()
{
  yyprintf((stderr, "%s\n", "WS"));
  l105:;	
  {  int yypos106= yypos, yythunkpos106= yythunkpos;
  {  int yypos107= yypos, yythunkpos107= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l108;  goto l107;
  l108:;	  yypos= yypos107; yythunkpos= yythunkpos107;  if (!yy_EOL()) goto l106;
  }
  l107:;	  goto l105;
  l106:;	  yypos= yypos106; yythunkpos= yythunkpos106;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "WS", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_Stmt()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Stmt"));
  {  int yypos110= yypos, yythunkpos110= yythunkpos;  if (!yy_WS()) goto l111;  if (!yy_Decl()) goto l111;  yyDo(yySet, -2, 0);  if (!yy_EOL()) goto l111;  goto l110;
  l111:;	  yypos= yypos110; yythunkpos= yythunkpos110;  if (!yy_WS()) goto l112;  if (!yy_Expr()) goto l112;  yyDo(yySet, -1, 0);  if (!yy_EOL()) goto l112;  goto l110;
  l112:;	  yypos= yypos110; yythunkpos= yythunkpos110;  if (!yy_WS()) goto l109;
  l113:;	
  {  int yypos114= yypos, yythunkpos114= yythunkpos;
  {  int yypos115= yypos, yythunkpos115= yythunkpos;  if (!yy_EOL()) goto l115;  goto l114;
  l115:;	  yypos= yypos115; yythunkpos= yythunkpos115;
  }  if (!yymatchDot()) goto l114;  goto l113;
  l114:;	  yypos= yypos114; yythunkpos= yythunkpos114;
  }  if (!yy_EOL()) goto l109;  yyDo(yy_1_Stmt, yybegin, yyend);
  }
  l110:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Stmt", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l109:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Stmt", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_Stmt);
}

#endif


int Parser_parse(char *pathArg) {
    /* Parse code */
    path = pathArg;
    stream = FileReader_new_withName(path);
    yylineno = 0;
    while (yyparse()) {}
    return 0;
}

