/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 32

#include <stdio.h>

/* ooc/rock imports */
#include <sdk/lang/BasicTypes-fwd.h>
#include <sdk/io/FileReader.h>

#include <source/rock/middle/Parenthesis-fwd.h>
#include <source/rock/middle/Type-fwd.h>
#include <source/rock/middle/Line-fwd.h>
#include <source/rock/middle/Node-fwd.h>
#include <source/rock/middle/StringLiteral-fwd.h>
#include <source/rock/middle/VariableAccess-fwd.h>
#include <source/rock/middle/IntLiteral-fwd.h>
#include <source/rock/middle/BinaryOp.h> // tight dependency: we use static members
#include <source/rock/middle/FunctionCall-fwd.h>
#include <source/rock/middle/FunctionDecl-fwd.h>
#include <source/rock/middle/CoverDecl-fwd.h>

#define YYSTYPE struct _rock_middle__Node*

// uncomment to enable leg's finicky debug output
//#define YY_DEBUG 1

/* Functions to communicate with rock */
void stack_push(struct _rock_middle__Node *node);
struct _rock_middle__Node *stack_pop(struct _lang__Class *);
void stack_add(struct _rock_middle__Node *node);

/* Current line number */
static int yylineno;

/* Path of the file we're parsing. */
static char* path;
 
/* The stream we're reading from. */
static struct _io__FileReader *stream;

/* Send input to yyparse from codebuf instead of stdin */
#define YY_INPUT(buf, result, max_size) {        \
	int yyc;                                     \
	if (FileReader_hasNext(stream))              \
		yyc= FileReader_read_char(stream);       \
	else                                         \
		yyc= EOF;                                \
	result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1); \
}


#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_STRING_LIT(); /* 32 */
YY_RULE(int) yy_NUMBER(); /* 31 */
YY_RULE(int) yy_DIV(); /* 30 */
YY_RULE(int) yy_TIMES(); /* 29 */
YY_RULE(int) yy_Value(); /* 28 */
YY_RULE(int) yy_MINUS(); /* 27 */
YY_RULE(int) yy_PLUS(); /* 26 */
YY_RULE(int) yy_Product(); /* 25 */
YY_RULE(int) yy_COMMA(); /* 24 */
YY_RULE(int) yy_CLOS_PAREN(); /* 23 */
YY_RULE(int) yy_ExpressionList(); /* 22 */
YY_RULE(int) yy_OPEN_PAREN(); /* 21 */
YY_RULE(int) yy_ASSIGN(); /* 20 */
YY_RULE(int) yy_VariableAccess(); /* 19 */
YY_RULE(int) yy_Type(); /* 18 */
YY_RULE(int) yy_CLOS_BRACK(); /* 17 */
YY_RULE(int) yy_Line(); /* 16 */
YY_RULE(int) yy_OPEN_BRACK(); /* 15 */
YY_RULE(int) yy_Body(); /* 14 */
YY_RULE(int) yy__(); /* 13 */
YY_RULE(int) yy_COLON(); /* 12 */
YY_RULE(int) yy_IDENT(); /* 11 */
YY_RULE(int) yy_FunctionDecl(); /* 10 */
YY_RULE(int) yy_Sum(); /* 9 */
YY_RULE(int) yy_FunctionCall(); /* 8 */
YY_RULE(int) yy_VariableDecl(); /* 7 */
YY_RULE(int) yy_Assignment(); /* 6 */
YY_RULE(int) yy_Decl(); /* 5 */
YY_RULE(int) yy_EOL(); /* 4 */
YY_RULE(int) yy_Expr(); /* 3 */
YY_RULE(int) yy_WS(); /* 2 */
YY_RULE(int) yy_Stmt(); /* 1 */

YY_ACTION(void) yy_1_EOL(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_EOL\n"));
   yylineno++ ;
}
YY_ACTION(void) yy_1_IDENT(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_IDENT\n"));
   yy=String_clone(yytext); ;
}
YY_ACTION(void) yy_1_STRING_LIT(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_STRING_LIT\n"));
   yy=StringLiteral_new_stringLiteral(String_clone(yytext), nullToken); ;
}
YY_ACTION(void) yy_1_NUMBER(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_NUMBER\n"));
   yy=IntLiteral_new_intLiteral(atoll(yytext), nullToken); ;
}
YY_ACTION(void) yy_2_Value(char *yytext, int yyleng)
{
#define inner yyval[-1]
#define name yyval[-2]
#define i yyval[-3]
  yyprintf((stderr, "do yy_2_Value\n"));
  
            yy=Parenthesis_new_parenthesis(inner, nullToken)
        ;
#undef inner
#undef name
#undef i
}
YY_ACTION(void) yy_1_Value(char *yytext, int yyleng)
{
#define inner yyval[-1]
#define name yyval[-2]
#define i yyval[-3]
  yyprintf((stderr, "do yy_1_Value\n"));
  
            yy=VariableAccess_new_variableAccess(name, nullToken)
        ;
#undef inner
#undef name
#undef i
}
YY_ACTION(void) yy_2_Product(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_2_Product\n"));
  
                    yy=BinaryOp_new_binaryOp(l, r, ((struct _rock_middle__OpTypesClass *) OpTypes_class())->div, nullToken);
                ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_Product(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_Product\n"));
  
                    yy=BinaryOp_new_binaryOp(l, r, ((struct _rock_middle__OpTypesClass *) OpTypes_class())->mul, nullToken);
                ;
#undef r
#undef l
}
YY_ACTION(void) yy_2_Sum(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_2_Sum\n"));
  
                    yy=BinaryOp_new_binaryOp(l, r, ((struct _rock_middle__OpTypesClass *) OpTypes_class())->sub, nullToken);
                ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_Sum(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_Sum\n"));
  
                    yy=BinaryOp_new_binaryOp(l, r, ((struct _rock_middle__OpTypesClass *) OpTypes_class())->add, nullToken);
                ;
#undef r
#undef l
}
YY_ACTION(void) yy_2_ExpressionList(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_ExpressionList\n"));
   stack_add(yy) ;
}
YY_ACTION(void) yy_1_ExpressionList(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_ExpressionList\n"));
   stack_add(yy) ;
}
YY_ACTION(void) yy_2_FunctionCall(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_FunctionCall\n"));
  
        yy = stack_pop(FunctionCall_class());
    ;
}
YY_ACTION(void) yy_1_FunctionCall(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_FunctionCall\n"));
  
        stack_push(FunctionCall_new_funcCall(String_clone(yytext), nullToken));
    ;
}
YY_ACTION(void) yy_1_VariableAccess(char *yytext, int yyleng)
{
#define name yyval[-1]
  yyprintf((stderr, "do yy_1_VariableAccess\n"));
   yy=VariableAccess_new_variableAccess(name, nullToken); ;
#undef name
}
YY_ACTION(void) yy_1_Assignment(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_Assignment\n"));
   yy=BinaryOp_new_binaryOp(l, r, ((struct _rock_middle__OpTypesClass *) OpTypes_class())->ass, nullToken); ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_Type(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_Type\n"));
   yy=BaseType_new_baseType(String_clone(yytext), nullToken) ;
}
YY_ACTION(void) yy_1_VariableDecl(char *yytext, int yyleng)
{
#define type yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_VariableDecl\n"));
  
        printf("Got a variable declaration with name = %s and type = %s\n", name, Node_toString(type));
        yy=VariableDecl_new_vDeclWithAtom(type, Atom_new_name(name), nullToken)
    ;
#undef type
#undef name
}
YY_ACTION(void) yy_1_Line(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_Line\n"));
   stack_add(Line_new_line(yy)); ;
#undef e
}
YY_ACTION(void) yy_2_FunctionDecl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_FunctionDecl\n"));
  
        stack_pop(FunctionDecl_class())
    ;
}
YY_ACTION(void) yy_1_FunctionDecl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_FunctionDecl\n"));
  
        printf("<functionDecl '%s'>\n", yytext);
        stack_push(FunctionDecl_new_funcDecl(String_clone(yytext), nullToken));
    ;
}
YY_ACTION(void) yy_1_Expr(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_Expr\n"));
   printf("skipped comment %s\n", yytext) ;
}
YY_ACTION(void) yy_1_Stmt(char *yytext, int yyleng)
{
#define d yyval[-1]
#define e yyval[-2]
  yyprintf((stderr, "do yy_1_Stmt\n"));
   printf("error at line %d: unexpected input '%s'\n", yylineno, yytext); exit(1); ;
#undef d
#undef e
}

YY_RULE(int) yy_STRING_LIT()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "STRING_LIT"));  if (!yymatchChar('"')) goto l1;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l1;
  l2:;	
  {  int yypos3= yypos, yythunkpos3= yythunkpos;
  {  int yypos4= yypos, yythunkpos4= yythunkpos;  if (!yymatchChar('"')) goto l4;  goto l3;
  l4:;	  yypos= yypos4; yythunkpos= yythunkpos4;
  }  if (!yymatchDot()) goto l3;  goto l2;
  l3:;	  yypos= yypos3; yythunkpos= yythunkpos3;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l1;  if (!yymatchChar('"')) goto l1;  if (!yy__()) goto l1;  yyDo(yy_1_STRING_LIT, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING_LIT", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING_LIT", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_NUMBER()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "NUMBER"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l5;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l5;
  l6:;	
  {  int yypos7= yypos, yythunkpos7= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l7;  goto l6;
  l7:;	  yypos= yypos7; yythunkpos= yythunkpos7;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l5;  if (!yy__()) goto l5;  yyDo(yy_1_NUMBER, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMBER", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMBER", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_DIV()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "DIV"));  if (!yymatchChar('/')) goto l8;  if (!yy__()) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "DIV", yybuf+yypos));
  return 1;
  l8:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DIV", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_TIMES()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "TIMES"));  if (!yymatchChar('*')) goto l9;  if (!yy__()) goto l9;
  yyprintf((stderr, "  ok   %s @ %s\n", "TIMES", yybuf+yypos));
  return 1;
  l9:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TIMES", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Value()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "Value"));
  {  int yypos11= yypos, yythunkpos11= yythunkpos;  if (!yy_NUMBER()) goto l12;  yyDo(yySet, -3, 0);  goto l11;
  l12:;	  yypos= yypos11; yythunkpos= yythunkpos11;  if (!yy_STRING_LIT()) goto l13;  yyDo(yySet, -3, 0);  goto l11;
  l13:;	  yypos= yypos11; yythunkpos= yythunkpos11;  if (!yy_IDENT()) goto l14;  yyDo(yySet, -2, 0);
  {  int yypos15= yypos, yythunkpos15= yythunkpos;  if (!yy_ASSIGN()) goto l15;  goto l14;
  l15:;	  yypos= yypos15; yythunkpos= yythunkpos15;
  }  yyDo(yy_1_Value, yybegin, yyend);  goto l11;
  l14:;	  yypos= yypos11; yythunkpos= yythunkpos11;  if (!yy_OPEN_PAREN()) goto l10;  if (!yy_Expr()) goto l10;  yyDo(yySet, -1, 0);  if (!yy_CLOS_PAREN()) goto l10;  yyDo(yy_2_Value, yybegin, yyend);
  }
  l11:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Value", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l10:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Value", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_MINUS()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "MINUS"));  if (!yymatchChar('-')) goto l16;  if (!yy__()) goto l16;
  yyprintf((stderr, "  ok   %s @ %s\n", "MINUS", yybuf+yypos));
  return 1;
  l16:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MINUS", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_PLUS()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "PLUS"));  if (!yymatchChar('+')) goto l17;  if (!yy__()) goto l17;
  yyprintf((stderr, "  ok   %s @ %s\n", "PLUS", yybuf+yypos));
  return 1;
  l17:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLUS", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Product()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Product"));  if (!yy_Value()) goto l18;  yyDo(yySet, -2, 0);
  l19:;	
  {  int yypos20= yypos, yythunkpos20= yythunkpos;
  {  int yypos21= yypos, yythunkpos21= yythunkpos;  if (!yy_TIMES()) goto l22;  if (!yy_Value()) goto l22;  yyDo(yySet, -1, 0);  yyDo(yy_1_Product, yybegin, yyend);  goto l21;
  l22:;	  yypos= yypos21; yythunkpos= yythunkpos21;  if (!yy_DIV()) goto l20;  if (!yy_Value()) goto l20;  yyDo(yySet, -1, 0);  yyDo(yy_2_Product, yybegin, yyend);
  }
  l21:;	  goto l19;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Product", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l18:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Product", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_COMMA()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "COMMA"));  if (!yymatchChar(',')) goto l23;  if (!yy__()) goto l23;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMA", yybuf+yypos));
  return 1;
  l23:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMA", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CLOS_PAREN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOS_PAREN"));  if (!yymatchChar(')')) goto l24;  if (!yy__()) goto l24;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOS_PAREN", yybuf+yypos));
  return 1;
  l24:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOS_PAREN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ExpressionList()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ExpressionList"));  if (!yy_Expr()) goto l25;  yyDo(yy_1_ExpressionList, yybegin, yyend);
  l26:;	
  {  int yypos27= yypos, yythunkpos27= yythunkpos;  if (!yy_COMMA()) goto l27;  if (!yy_Expr()) goto l27;  yyDo(yy_2_ExpressionList, yybegin, yyend);  goto l26;
  l27:;	  yypos= yypos27; yythunkpos= yythunkpos27;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "ExpressionList", yybuf+yypos));
  return 1;
  l25:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ExpressionList", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OPEN_PAREN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN_PAREN"));  if (!yymatchChar('(')) goto l28;  if (!yy__()) goto l28;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_PAREN", yybuf+yypos));
  return 1;
  l28:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_PAREN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ASSIGN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ASSIGN"));  if (!yymatchChar('=')) goto l29;  if (!yy__()) goto l29;
  yyprintf((stderr, "  ok   %s @ %s\n", "ASSIGN", yybuf+yypos));
  return 1;
  l29:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ASSIGN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_VariableAccess()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "VariableAccess"));  if (!yy_IDENT()) goto l30;  yyDo(yySet, -1, 0);  if (!yy__()) goto l30;  yyDo(yy_1_VariableAccess, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "VariableAccess", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l30:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VariableAccess", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Type()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Type"));  if (!yy_IDENT()) goto l31;  yyDo(yy_1_Type, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "Type", yybuf+yypos));
  return 1;
  l31:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Type", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CLOS_BRACK()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOS_BRACK"));  if (!yymatchChar('}')) goto l32;  if (!yy__()) goto l32;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOS_BRACK", yybuf+yypos));
  return 1;
  l32:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOS_BRACK", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Line"));  if (!yy_WS()) goto l33;
  {  int yypos34= yypos, yythunkpos34= yythunkpos;  if (!yy_EOL()) goto l34;  goto l33;
  l34:;	  yypos= yypos34; yythunkpos= yythunkpos34;
  }  if (!yy_Expr()) goto l33;  yyDo(yySet, -1, 0);
  l35:;	
  {  int yypos36= yypos, yythunkpos36= yythunkpos;  if (!yy_EOL()) goto l36;  goto l35;
  l36:;	  yypos= yypos36; yythunkpos= yythunkpos36;
  }  yyDo(yy_1_Line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "Line", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OPEN_BRACK()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN_BRACK"));  if (!yymatchChar('{')) goto l37;  if (!yy__()) goto l37;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_BRACK", yybuf+yypos));
  return 1;
  l37:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_BRACK", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Body"));  if (!yy_OPEN_BRACK()) goto l38;
  l39:;	
  {  int yypos40= yypos, yythunkpos40= yythunkpos;  if (!yy_EOL()) goto l40;  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }
  l41:;	
  {  int yypos42= yypos, yythunkpos42= yythunkpos;  if (!yy_Line()) goto l42;  goto l41;
  l42:;	  yypos= yypos42; yythunkpos= yythunkpos42;
  }  if (!yy_CLOS_BRACK()) goto l38;  if (!yy__()) goto l38;
  yyprintf((stderr, "  ok   %s @ %s\n", "Body", yybuf+yypos));
  return 1;
  l38:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Body", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{
  yyprintf((stderr, "%s\n", "_"));
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l45;  goto l44;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_COLON()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "COLON"));  if (!yymatchChar(':')) goto l46;  if (!yy__()) goto l46;
  yyprintf((stderr, "  ok   %s @ %s\n", "COLON", yybuf+yypos));
  return 1;
  l46:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COLON", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_IDENT()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "IDENT"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l47;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l47;
  l48:;	
  {  int yypos49= yypos, yythunkpos49= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l49;  goto l48;
  l49:;	  yypos= yypos49; yythunkpos= yythunkpos49;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l47;  if (!yy__()) goto l47;  yyDo(yy_1_IDENT, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT", yybuf+yypos));
  return 1;
  l47:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_FunctionDecl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "FunctionDecl"));  if (!yy_IDENT()) goto l50;  yyDo(yy_1_FunctionDecl, yybegin, yyend);  if (!yy_COLON()) goto l50;  if (!yymatchString("func")) goto l50;  if (!yy__()) goto l50;
  {  int yypos51= yypos, yythunkpos51= yythunkpos;  if (!yy_Body()) goto l51;  goto l52;
  l51:;	  yypos= yypos51; yythunkpos= yythunkpos51;
  }
  l52:;	  if (!yy__()) goto l50;  yyDo(yy_2_FunctionDecl, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "FunctionDecl", yybuf+yypos));
  return 1;
  l50:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FunctionDecl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Sum()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Sum"));  if (!yy_Product()) goto l53;  yyDo(yySet, -2, 0);
  l54:;	
  {  int yypos55= yypos, yythunkpos55= yythunkpos;
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yy_PLUS()) goto l57;  if (!yy_Product()) goto l57;  yyDo(yySet, -1, 0);  yyDo(yy_1_Sum, yybegin, yyend);  goto l56;
  l57:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yy_MINUS()) goto l55;  if (!yy_Product()) goto l55;  yyDo(yySet, -1, 0);  yyDo(yy_2_Sum, yybegin, yyend);
  }
  l56:;	  goto l54;
  l55:;	  yypos= yypos55; yythunkpos= yythunkpos55;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Sum", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l53:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Sum", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_FunctionCall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "FunctionCall"));  if (!yy_IDENT()) goto l58;  yyDo(yy_1_FunctionCall, yybegin, yyend);  if (!yy_OPEN_PAREN()) goto l58;
  {  int yypos59= yypos, yythunkpos59= yythunkpos;  if (!yy_ExpressionList()) goto l59;  goto l60;
  l59:;	  yypos= yypos59; yythunkpos= yythunkpos59;
  }
  l60:;	  if (!yy_CLOS_PAREN()) goto l58;  if (!yy__()) goto l58;  yyDo(yy_2_FunctionCall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "FunctionCall", yybuf+yypos));
  return 1;
  l58:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FunctionCall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_VariableDecl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "VariableDecl"));  if (!yy_IDENT()) goto l61;  yyDo(yySet, -2, 0);  if (!yy_COLON()) goto l61;  if (!yy_Type()) goto l61;  yyDo(yySet, -1, 0);  yyDo(yy_1_VariableDecl, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "VariableDecl", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l61:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VariableDecl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Assignment()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Assignment"));  if (!yy_VariableAccess()) goto l62;  yyDo(yySet, -2, 0);  if (!yy_ASSIGN()) goto l62;  if (!yy_Expr()) goto l62;  yyDo(yySet, -1, 0);  if (!yy__()) goto l62;  yyDo(yy_1_Assignment, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "Assignment", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l62:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Assignment", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Decl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Decl"));
  {  int yypos64= yypos, yythunkpos64= yythunkpos;  if (!yy_FunctionDecl()) goto l65;  goto l64;
  l65:;	  yypos= yypos64; yythunkpos= yythunkpos64;  if (!yy_VariableDecl()) goto l63;
  }
  l64:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Decl", yybuf+yypos));
  return 1;
  l63:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Decl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_EOL()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos67= yypos, yythunkpos67= yythunkpos;
  {  int yypos69= yypos, yythunkpos69= yythunkpos;  if (!yymatchChar('\n')) goto l70;  goto l69;
  l70:;	  yypos= yypos69; yythunkpos= yythunkpos69;  if (!yymatchString("\r\n")) goto l71;  goto l69;
  l71:;	  yypos= yypos69; yythunkpos= yythunkpos69;  if (!yymatchChar('\r')) goto l68;
  }
  l69:;	  yyDo(yy_1_EOL, yybegin, yyend);  goto l67;
  l68:;	  yypos= yypos67; yythunkpos= yythunkpos67;  if (!yymatchChar(';')) goto l66;
  }
  l67:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yybuf+yypos));
  return 1;
  l66:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Expr"));
  {  int yypos73= yypos, yythunkpos73= yythunkpos;  if (!yy_Assignment()) goto l74;  goto l73;
  l74:;	  yypos= yypos73; yythunkpos= yythunkpos73;  if (!yy_VariableDecl()) goto l75;  goto l73;
  l75:;	  yypos= yypos73; yythunkpos= yythunkpos73;  if (!yy_FunctionCall()) goto l76;  goto l73;
  l76:;	  yypos= yypos73; yythunkpos= yythunkpos73;  if (!yy_Sum()) goto l77;  goto l73;
  l77:;	  yypos= yypos73; yythunkpos= yythunkpos73;  if (!yy_WS()) goto l72;  if (!yymatchString("//")) goto l72;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l72;
  l78:;	
  {  int yypos79= yypos, yythunkpos79= yythunkpos;
  {  int yypos80= yypos, yythunkpos80= yythunkpos;  if (!yy_EOL()) goto l80;  goto l79;
  l80:;	  yypos= yypos80; yythunkpos= yythunkpos80;
  }  if (!yymatchDot()) goto l79;  goto l78;
  l79:;	  yypos= yypos79; yythunkpos= yythunkpos79;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l72;  if (!yy_EOL()) goto l72;  if (!yy_WS()) goto l72;  yyDo(yy_1_Expr, yybegin, yyend);
  {  int yypos81= yypos, yythunkpos81= yythunkpos;  if (!yy_Expr()) goto l81;  goto l82;
  l81:;	  yypos= yypos81; yythunkpos= yythunkpos81;
  }
  l82:;	
  }
  l73:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Expr", yybuf+yypos));
  return 1;
  l72:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_WS()
{
  yyprintf((stderr, "%s\n", "WS"));
  l84:;	
  {  int yypos85= yypos, yythunkpos85= yythunkpos;
  {  int yypos86= yypos, yythunkpos86= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l87;  goto l86;
  l87:;	  yypos= yypos86; yythunkpos= yythunkpos86;  if (!yy_EOL()) goto l85;
  }
  l86:;	  goto l84;
  l85:;	  yypos= yypos85; yythunkpos= yythunkpos85;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "WS", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_Stmt()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Stmt"));
  {  int yypos89= yypos, yythunkpos89= yythunkpos;  if (!yy_WS()) goto l90;  if (!yy_Expr()) goto l90;  yyDo(yySet, -2, 0);  if (!yy_EOL()) goto l90;  goto l89;
  l90:;	  yypos= yypos89; yythunkpos= yythunkpos89;  if (!yy_WS()) goto l91;  if (!yy_Decl()) goto l91;  yyDo(yySet, -1, 0);  if (!yy_EOL()) goto l91;  goto l89;
  l91:;	  yypos= yypos89; yythunkpos= yythunkpos89;
  l92:;	
  {  int yypos93= yypos, yythunkpos93= yythunkpos;
  {  int yypos94= yypos, yythunkpos94= yythunkpos;  if (!yy_EOL()) goto l94;  goto l93;
  l94:;	  yypos= yypos94; yythunkpos= yythunkpos94;
  }  if (!yymatchDot()) goto l93;  goto l92;
  l93:;	  yypos= yypos93; yythunkpos= yythunkpos93;
  }  if (!yy_EOL()) goto l88;  yyDo(yy_1_Stmt, yybegin, yyend);
  }
  l89:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Stmt", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l88:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Stmt", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_Stmt);
}

#endif


int Parser_parse(char *pathArg) {
    /* Parse code */
    path = pathArg;
    stream = FileReader_new_withName(path);
    yylineno = 0;
    while (yyparse()) {}
    return 0;
}

